### ISSUE TITLE
GoLang SDK release

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/supertokens-golang#14]
Create and release the golang SDK

TODO:
- [x] Create golang ID on the backend and remove go ID
- [x] Make the go repo deprecated and link it to golang repo
- [x] Push docs to production
- [x] Build supertokens-website server
- [x] Build supertokens-auth-react server
- [x] Setup CICD for repo
- [x] Check if we have blocking release of core if golang is not updated with new CDI in future?
- [x] Put it on the main golang distribution site
- [x] Check if telemetry is working or not
- [x] Check why handshake info and verifySession is being called so many times.
- [x] UTF-8 compatibility for JWT decoding
